spring.application.name=12_jpa_tutorial

spring.datasource.url = jdbc:postgresql://localhost:5432/student_db

spring.datasource.username = postgres
spring.datasource.password = Temp@123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
