spring.application.name=security-app


spring.datasource.url = jdbc:postgresql://localhost:5432/student_security_db
spring.datasource.username = postgres
spring.datasource.password = Temp@123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.expiration=900000
jwt.secret=tYw1YSTkVEcp3DjfTOLbFu3otURtnSFoCR0GgeazDQP1eI5Eh9cVLHmpa3t9BKOxGpb27ARjHBHYpwiiY2E8Kw==