spring.application.name=api-gateway

server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Employee route
spring.cloud.gateway.server.webmvc.routes[0].id=employee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://employee-microservice
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/employee/**

# Department route
spring.cloud.gateway.server.webmvc.routes[1].id=department-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://department-microservice
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/department/**